### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by nazimboudeffa** [xmxstudio/js-tic-tac-toe-no-arrays#1]
Hi,

Is there a wiki for this game ?

Thx

**Comment by xmxstudio** [comment]
There is no wiki. I can create one I guess. I've never created one. Lets see how this goes.

**Comment by xmxstudio** [comment]
[https://github.com/xmxstudio/js-tic-tac-toe-no-arrays/wiki/https:--github.com-xmxstudio-js-tic-tac-toe-no-arrays-wiki-_newHome](https://github.com/xmxstudio/js-tic-tac-toe-no-arrays/wiki/https:--github.com-xmxstudio-js-tic-tac-toe-no-arrays-wiki-_newHome)
